#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $storm-nimbus
# chkconfig: - 64 36
# description:  Storm Nimbus service.
# processname: storm-nimbus
# pidfile: /var/run/storm-nimbus.pid

### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=root
PID_FILE="/var/run/storm-nimbus.pid"

STORM_HOME="/opt/storm"
LIB="$STORM_HOME/lib"
STORM_JAR=($STORM_HOME/storm-core*.jar)
STORM_CONF="$STORM_HOME/conf"
STORM_LOG="$STORM_HOME/logs"

CLASSPATH="$LIB/*:$STORM_JAR:$STORM_CONF:$STORM_LOG"

JVM_TYPE="server"
NIMBUS_JVM_MEMORY="1024m"
NIMBUS_JVM_OPTS=""

# Source config
. /etc/sysconfig/storm

start() {
    if storm_status $PID_FILE; then
        echo "Storm nimbus instance already running"
        return 0
    else
        echo "Starting storm nimbus..."
    fi 
    STORM_CMD="java -$JVM_TYPE -Xmx$NIMBUS_JVM_MEMORY -Djava.library.path=\"$JAVA_LIBRARY_PATH\" -Dstorm.options=\"$STORM_OPTIONS\" -Dstorm.home=\"$STORM_HOME\" -Dstorm.log.dir=/var/log/storm -Dlogback.configurationFile=${STORM_HOME}/logback/cluster.xml -Dlogfile.name=nimbus.log $NIMBUS_JVM_OPTS -cp \"$CLASSPATH\" backtype.storm.daemon.nimbus &"
    daemon "$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    print_storm_status $PID_FILE
    return $RETVAL
}

stop() {
    if storm_status $PID_FILE; then
        echo "Stopping storm nimbus..."
    else
        echo "Storm nimbus is not running."
        return 3
    fi
    killproc -p $PID_FILE -TERM
    print_storm_status $PID_FILE
    return $?
}

storm_check_pid() {
    local pid=$1
    ps -fp $pid | grep $pid | grep nimbus > /dev/null 2>&1
    return $?
}

storm_status() {
    local pidfile="$1" # IN
    local pid=`cat "$pidfile" 2>/dev/null`
    if [ "$pid" = '' ]; then
        # The file probably does not exist or is empty. 
        return 1
    fi

    set -- $pid
    pid="$1"

    storm_check_pid $pid
    return $?
}

print_storm_status() {
    if storm_status $PID_FILE; then
        echo "Storm nimbus is running."	
        return 0
    else
        echo "Storm nimbus is stopped."
        return 3
    fi
}

restart() {
    stop
    start
}

reload()  {
    restart
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        print_storm_status
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?
