#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $storm-drpc
# chkconfig: - 64 36
# description:  Storm DRPC service.
# processname: storm-drpc
# pidfile: /var/run/storm-drpc.pid
### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=root
PID_FILE="/var/run/storm-drpc.pid"

STORM_HOME="/opt/storm"
LIB="$STORM_HOME/lib"
STORM_JARS1=($STORM_HOME/storm-console-logging*.jar)
STORM_JARS2=($STORM_HOME/storm-netty*.jar)
STORM_JARS3=($STORM_HOME/storm-core*.jar)
STORM_JARS=${STORM_JARS1}:${STORM_JARS2}:${STORM_JARS3}
STORM_CONF="$STORM_HOME/conf"
STORM_LOG="$STORM_HOME/logs"

CLASSPATH="$STORM_JARS:$LIB/*:$STORM_CONF:$STORM_LOG"

JVM_TYPE="server"
SUPERVISOR_JVM_MEMORY="1024m"
SUPERVISOR_JVM_OPTS=""

# Source config
. /etc/sysconfig/storm

start() {
    if storm_status $PID_FILE; then
        echo "Error storm drpc instance already running"
        return 0
    else
        echo "Starting storm drpc..."
    fi 
    STORM_CMD="java -$JVM_TYPE -Xmx$SUPERVISOR_JVM_MEMORY -Djava.library.path=\"$JAVA_LIBRARY_PATH\" -Dstorm.options=\"$STORM_OPTIONS\" -Dstorm.home=\"$STORM_HOME\" -Dlogback.configurationFile=${STORM_HOME}/logback/cluster.xml -Dlogfile.name=drpc.log $SUPERVISOR_JVM_OPTS -cp \"$CLASSPATH\" backtype.storm.daemon.drpc &"
    daemon "$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    print_storm_status $PID_FILE
    return $RETVAL
}

stop() {
    if storm_status $PID_FILE; then
        echo "Stopping storm drpc..."
    else
        echo "Storm drpc is not running."
        return 0
    fi
    killproc -p $PID_FILE -TERM
    print_storm_status $PID_FILE
    return $?
}

storm_check_pid() {
    local pid=$1
    ps -fp $pid | grep $pid | grep drpc > /dev/null 2>&1
}

storm_status() {
    local pidfile="$1" # IN
    local pid=`cat "$pidfile" 2>/dev/null`
    if [ "$pid" = '' ]; then
        # The file probably does not exist or is empty. 
        return 1
    fi

    set -- $pid
    pid="$1"

    storm_check_pid $pid
}

print_storm_status() {
    if storm_status $PID_FILE; then
        echo "Storm drpc is running."
    else
        echo "Storm drpc is stopped."
    fi
}

restart() {
    stop
    start
}

reload()  {
    restart
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        print_storm_status
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?
